# Use the R package with docs at: https://docs.travis-ci.com/user/languages/r
language: r

# Store packages to avoid redownloading
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/docs"

# Go to container architecture
sudo: false

# For CRAN...
warnings_are_errors: true

# Let's create a build matrix!
# matrix:
#  include:
#  - os: linux
#    dist: precise
#    sudo: false
#    r: oldrel
#  - os: linux
#    dist: precise
#    sudo: false
#    r: release
#  - os: linux
#    dist: precise
#    sudo: false
#    r: devel
#  - os: linux
#    dist: trusty
#    sudo: true
#    r: oldrel
#  - os: linux
#    dist: trusty
#    sudo: true
#    r: release
#  - os: linux
#    dist: trusty
#    sudo: true
#    r: devel

# Write documentation to new branch
r_github_packages:
- klutometis/roxygen
- hadley/staticdocs

before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash _build.sh && bash
  _deploy.sh

# Use SMAC's GitHub PAT token
env:
  global:
    secure: Uv2vIsl/YzDJOs/HxzTayopE9KDROspfQ28jkfc+A098HxWtoPrDdzXujCNZp1OaYrNJzkMnGAgtvFTxyynt0GO1PoHzAsnIo9J5lhlapNDWD0E2I88fm4H2TU8UOaX1LKoqzXhUuJ9EnOHAUDwTs+Fv34sDSXY86jv+RDgkK7o8l2kQku59ursqvWDDLgpKV+IR4E4XT+gkATD91b+Kx1aMUzcCR5cbKAjK9I7GW6CGUMKbskhRaqL4wa6uHXVBWfupx81vaImAhE3pdVo65xHouMxoc3kK/1ggqBKDv3fn4Ir42mseRfLDGm+4zXVbm2Q0p7zfrg05h5IZ8nA2R6AnxnXc9fGIxXk2MuhmAvNZZ1lZDrSGPZYCHRf6vNJXlS3v0FKf3y2fJuj8auUf6untWB2+eLkH7g90sAPgjXGhj9Fy80MecglE9t9AxLNWrpgA43+aT7q1QWbzsalYnAtIpX1LSKaPnKpCo1HkeGOPOSU+7uHAxlxUB/eh5VTRo+bDW6luM4KSRrfpPKbcNBE1wpSKYPp5RSpzGyK8SaG08Lp83rUzxxXlY3DB0r9Y0sKtkwvJbXx8oh0f1QlHNfCuk9JC8HO4EZBmteuNX512u+Ef54OD39TV58fvoJOSAiIoIdbHxuZl6Xs70bhZI3FyLo44swE30pvUq3BRxFw=
notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: uiN+o7CRNd2yiIZ0KoOYF/hrLQxW2q95MKNccjeQ30+t+N3gLS4iAuCoWi6CQzv/a4ADOKjKEY4/sBQiatBN7hVkwTgdizaU3hylmUuo124XkzGEMLYMxS5YgnQhud5PYxlLkucrKoKZ9vtA3sa0JRCmAdpBhVx71SysO4UlLp8ZMwaStBj5ygzmV7Iw874zhqHW8vv6Plr+KMGRoaUxy5w3cyVCXoQ9FowXvRGoxPhZFA/TxZRx8Ewoz7A8UFv1iBglXkhlqYRy9axUsm0sS5TNsinsbFAQUA887o9ZqUz5wrWlLTsF53qMbnqIcqmnyN0LGe9OXd38NOOzA0VhgE6ivs+XgxTfozBrdLdnj7pe6bLkCeN2lHogQjfgl3ZMd7/QSFU4P9ltgByju1LqeoC9TSLl7tP4DztcWeFe8xZf6Y8xXwRXxT4U75eBXy19svDt36e2VViiJGNolORpQW2Avdzi0cpkhxnjalE9C0k5RcKu6gSVu3udo7WktDlx945M/XrHjBXkXu2kcv8p3ljXoWn0x+MxubPIIqMLekaQAwFvsyO1c7VFkW6jkR39niz/wAaTk1tlLCUV8HBA1rWAahwdI/1v2lsrtA3v+vIRQaZl3Nj9wRsDJsAtt1RPReMGXXudymdyIeXQxUcZR8qoCQO9FKP3i1Wy21QwKfs=
