language: r
sudo: required
warnings_are_errors: true

r_packages:
 - ggplot2
 - RcppArmadillo
 - knitr
 - grid

before_script:
 - Rscript -e "devtools::install_github('SMAC-Group/imudata')"
 - Rscript -e "Rcpp::compileAttributes()"