language: r
sudo: required
warnings_are_errors: true

r_packages:
 - ggplot2
 - RcppArmadillo
 - knitr
 - gridExtra
 - grid

before_install:
 - sudo apt-get install -y libcurl-dev

before_script:
 -  Rscript -e "Rcpp::compileAttributes()"