language: r
sudo: required
warnings_are_errors: true

r_packages:
 - ggplot2
 - RcppArmadillo
 - knitr
 - gridExtra
 - grid

before_script:
 - Rscript -e "getOption('download.file.method'); capabilities('libcurl'); nzchar(Sys.which('wget')[1]); nzchar(Sys.which('curl')[1]);"
 - Rscript -e "Rcpp::compileAttributes()"